### PR TITLE
Adding a new song in feb to Queen

### PR DESCRIPTION
**Pull request by SantiagoGV29**

### CODE REVIEW

**Comment by SantiagoGV29** [comment]
Added a new song in feb to Queen artists

**Comment by d3latorre** [comment]
it looks fine

**Comment by SantiagoGV29** [comment]
It looks perfectly nice

**Comment by VeroAlomia** [comment]
Looks amazing!

**Comment by lauraaac** [comment]
OMG! without any doubt I approved!

**Review by VeroAlomia — APPROVED** [review]

**Pull request merged**
